### ISSUE TITLE
Reset Password - Alert messages issue

### ISSUE THREAD

**Issue by Rishika631** [vs22202/bp-castrol-workshop-front-end#42]
![reset password 2](https://github.com/vs22202/bp-castrol-workshop-front-end/assets/89201634/55b69961-5cec-48ad-b078-eee00513d8c0)

1. The alert message should have Sign Up instead of Signup. Alert message should be: User's email does not exist, please sign up instead.

![image](https://github.com/vs22202/bp-castrol-workshop-front-end/assets/89201634/f5f0df7f-3be1-4167-b193-a750024baa26)
 
2. The alert message spelling of regenerate needs to be corrected. Alert message should be: OTP expired, please regenerate.

![image](https://github.com/vs22202/bp-castrol-workshop-front-end/assets/89201634/1f1a68d7-2fe5-4e51-ba75-1ef4c743815e)

3. The alert message should have Sign Up instead of Signup. Alert message should be: "User's mobile number does not exist, please sign up instead."

**Comment by vs22202** [comment]
repo: #vs22202/bp-castrol-workshop-back-end PR: #22 fixes these issues
